import csv,html,json,pathlib
from site_updates import prepare, footer_status, script
metadata=prepare()
P=pathlib.Path(__file__).parent
D=[dict(r) for r in csv.DictReader((P/'data.tsv').open(encoding='utf-8'),delimiter='\t')]
def e(s):return html.escape(str(s or ''),quote=True)
DEPS={'DENGE':{'name':'Departamento de Engenharias','short':'Engenharias','id':'933','color':'#b84415','pale':'#fff3ec','number':'01'},'DCETI':{'name':'Departamento de Ciências Exatas e Tecnologia da Informação','short':'Ciências Exatas e Tecnologia da Informação','id':'932','color':'#067568','pale':'#eaf8f3','number':'02'},'DCH':{'name':'Departamento de Ciências Humanas','short':'Ciências Humanas','id':'934','color':'#733bb9','pale':'#f4effc','number':'03'}}
photos={}
if (P/'photos.json').exists():photos=json.loads((P/'photos.json').read_text(encoding='utf-8'))
sub={'3552919','3527688','1044779','3511726','1246564'}
def head(title,root='./'):return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Conheça os docentes de DENGE, DCETI e DCH da UFERSA, Campus Angicos. Formação, contatos e links acadêmicos."><title>'+e(title)+' | Docentes UFERSA Angicos</title><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 32 32%27%3E%3Crect width=%2732%27 height=%2732%27 rx=%277%27 fill=%27%231943c9%27/%3E%3Cpath d=%27M8 8v10a8 8 0 0016 0V8h-5v10a3 3 0 01-6 0V8z%27 fill=%27white%27/%3E%3C/svg%3E"><link rel="stylesheet" href="'+root+'style.css"></head>'
def nav(active='',root='./'):
 return '<a class="skip" href="#conteudo">Pular para o conteúdo</a><header class="top"><a class="brand" href="'+root+'"><span class="brandmark">U</span><span>UFERSA<span class="brand-sub">CAMPUS ANGICOS</span></span></a><nav aria-label="Navegação principal"><a href="'+root+'" '+('aria-current="page"' if not active else '')+'>Início</a>'+''.join('<a href="'+root+k.lower()+'/" '+('aria-current="page"' if k==active else '')+'>'+k+'</a>' for k in DEPS)+'</nav></header>'
def footer(root='./'):return '<footer><div><strong>Docentes · UFERSA Angicos</strong><p>Diretório de apresentação baseado nas páginas públicas do SIGAA.</p></div><div class="footnote"><span id="sync-freshness">'+footer_status(metadata)+'</span><br>Perfis e contatos: consulta original em 12/09/2026.<br>Confira as informa??es atuais no SIGAA.</div></footer>'+script(metadata,root)
def card(r,root='../'):
 photo=photos.get(r['id'],'')
 if photo.startswith('/') and not photo.startswith('//'):photo=root+photo.lstrip('/')
 initials=''.join(x[0] for x in r['name'].split()[:1]+r['name'].split()[-1:])
 pic='<div class="portrait"><span aria-hidden="true">'+e(initials)+'</span>'+(('<img src="'+e(photo)+'" alt="Foto de '+e(r['name'])+'" width="88" height="100" loading="lazy" onerror="this.remove()">') if photo else '')+'</div>'
 typ=r.get('status') or ('Cedido' if r['id'] in {'2400142','1278994'} else ('Substituto' if r['id'] in sub else 'Ativo permanente'))
 email='<a class="email" href="mailto:'+e(r['email'])+'">'+e(r['email'])+'</a>' if r['email'] else '<span class="unavailable">'+('Não disponível na consulta' if r['id'] in protected|failed else 'Não informado no SIGAA')+'</span>'
 formation=r['formation'] or ('Formação não disponível na consulta.' if r['id'] in failed else 'Formação não informada no SIGAA.')
 lat='<a class="lattes" href="'+e(r['lattes'])+'" target="_blank" rel="noopener noreferrer">Currículo Lattes <span aria-hidden="true">↗</span></a>' if r['lattes'] else '<span class="unavailable lattes-missing">Lattes '+('indisponível' if r['id'] in failed else 'não informado')+'</span>'
 return '<article class="card"><div class="card-top">'+pic+'<div><span class="degree">'+e(r['degree'] or 'Docente')+'</span><h2>'+e(r['name'])+'</h2><p class="status">'+e(typ)+'</p></div></div><div class="formation"><h3>Formação e atuação</h3><p>'+e(formation)+'</p></div><dl class="contact"><div><dt>E-mail</dt><dd>'+email+'</dd></div><div class="contact-pair"><div><dt>Telefone / ramal</dt><dd>'+e(r['phone'] or ('Não disponível na consulta' if r['id'] in failed else ('Cadastro sem número válido' if r['id'] in {'2075857','1890530','1816178','2213705'} else 'Não informado')))+'</dd></div><div><dt>Sala</dt><dd>'+e(r['room'] or ('Não disponível na consulta' if r['id'] in failed else 'Não informada'))+'</dd></div></div></dl><div class="card-actions">'+lat+'<a href="https://sigaa.ufersa.edu.br/sigaa/public/docente/portal.jsf?siape='+e(r['id'])+'" target="_blank" rel="noopener noreferrer">Página pessoal <span aria-hidden="true">↗</span></a></div>'+('<p class="profile-note">Perfil não carregou nesta consulta; dados da lista do departamento.</p>' if r['id'] in failed else '')+'</article>'
protected={'1763913','1998864','2725571','1378429','2089358','1059673','1292448','1055685'}
failed={'1477231','2045711','1674506','3552722','1473860','1764968','1565646','1238040','1507727'}
if (P/'status.json').exists():
 st=json.loads((P/'status.json').read_text(encoding='utf-8'));sub.update(st.get('sub',[]));protected.update(st.get('protected',[]));failed.update(st.get('failed',[]));failed.difference_update(st.get('recovered',[]))
for key,dep in DEPS.items():
 rows=[r for r in D if r['department']==key];dest=P/'dist'/key.lower();dest.mkdir(exist_ok=True)
 body=head(key,'../')+'<body style="--accent:'+dep['color']+';--pale:'+dep['pale']+'">'+nav(key,'../')+'<main id="conteudo"><div class="department-heading"><a class="back" href="../">← Todos os departamentos</a><div class="dept-title"><div><p class="eyebrow">UFERSA / CAMPUS ANGICOS</p><h1>'+key+'</h1><p class="department-name">'+dep['name']+'</p></div><div class="dept-count"><strong>'+str(len(rows))+'</strong><span>docentes</span></div></div></div><div class="section-heading"><h2>Corpo docente</h2><a href="https://sigaa.ufersa.edu.br/sigaa/public/departamento/professores.jsf?id='+dep['id']+'" target="_blank" rel="noopener noreferrer">Lista no SIGAA ↗</a></div><p class="source-note">Formação, contatos e perfis acadêmicos conforme disponíveis no SIGAA. Os links externos abrem em nova aba. As iniciais aparecem quando não há foto no cadastro.</p><div class="faculty-grid">'+''.join(card(r) for r in rows)+'</div></main>'+footer('../')+'</body></html>'
 (dest/'index.html').write_text(body,encoding='utf-8')
tiles=''
for key,dep in DEPS.items():
 tiles+='<a class="dept-tile" style="--accent:'+dep['color']+';--pale:'+dep['pale']+'" href="./'+key.lower()+'/"><div class="tile-top"><span>DEPARTAMENTO '+dep['number']+'</span><span class="tile-arrow" aria-hidden="true">↗</span></div><h2>'+key+'</h2><p>'+dep['short']+'</p><div class="tile-bottom"><span>'+str(sum(r['department']==key for r in D))+' docentes</span><strong>Conhecer docentes →</strong></div></a>'
(P/'dist/index.html').write_text(head('Conheça nosso corpo docente')+'<body class="home">'+nav()+'<main id="conteudo"><section class="intro"><div><p class="eyebrow">UNIVERSIDADE FEDERAL RURAL DO SEMI-ÁRIDO</p><h1>Conheça o<br><em>corpo docente.</em></h1><p class="intro-copy">Formação acadêmica e contatos dos docentes<br class="desktop"> do Campus Angicos.</p></div><div class="intro-numbers"><div><strong>'+str(len(D))+'</strong><span>docentes</span></div><div><strong>03</strong><span>departamentos</span></div></div></section><section aria-labelledby="dep-heading"><div class="section-heading"><h2 id="dep-heading">Explore por departamento</h2><span>Formação · Contatos · Currículos</span></div><div class="department-grid">'+tiles+'</div></section><aside class="information"><span class="info-icon" aria-hidden="true">i</span><p>Em cada cartão, encontre a formação, os contatos disponíveis e os acessos ao Currículo Lattes e à página pessoal no SIGAA.</p><span class="source-label">FONTE: SIGAA / UFERSA</span></aside></main>'+footer()+'</body></html>',encoding='utf-8')
print('Generated',len(D),'cards; departments:',{k:sum(r['department']==k for r in D) for k in DEPS})
